version = 0.1

[default.deploy.parameters]
stack_name = "eventpulse-dev"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=dev"
confirm_changeset = false
no_fail_on_empty_changeset = true